# Generated by Django 4.2 on 2023-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_ticketmodel_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='identification',
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/tickets'),
        ),
    ]
